### ISSUE TITLE
HD2S model should output the output after sigmoid

### ISSUE THREAD

**Issue by lcnature** [perceivelab/hd2s#1]
Hello,
We were trying your `test.py` code and initially found the heatmap output quite strange. After reading the `HD2S.py` code, we think the reason is that in [this line](https://github.com/perceivelab/hd2s/blob/00fed7441053dd5d1fc9b3234cebaef915171aee/models/HD2S.py#L85) `x` was returned instead of `out`. Because `x` is the logit, it can be negative. On the other hand, [this line](https://github.com/perceivelab/hd2s/blob/00fed7441053dd5d1fc9b3234cebaef915171aee/test.py#L156) apparently assumes the output of the model is positive. So it will produce strange heatmaps. Changing the model to return `out` fixed the problem.

**Comment by belli13** [comment]
Hi lcnature, 
I checked the code and yes, the model should return `out` instead of `x`, as you say. 
The code has been fixed. 
Thanks for the contribution.

**Comment by lcnature** [comment]
@belli13 Thanks for fixing the code!
