### ISSUE TITLE
Some questions about the results on Hollywood2 and UCFsports

### ISSUE THREAD

**Issue by GemLuo** [perceivelab/hd2s#2]
hi, i have some questions about the results on Hollywood2 and UCFsports.

1. The result for hd2s on dataset hollywood2  is train on dataset DHF1K's trainset, and test on dataset hollywood2's testset, right?
Because i view that the result of hd2s for one-source learning is different from the above result.
![image](https://user-images.githubusercontent.com/67355297/137276104-6e418b17-c765-4a15-9873-070fcf0d5bb2.png)
![image](https://user-images.githubusercontent.com/67355297/137277321-5582e847-75ef-4b7e-9f9d-de6e00fcc6dd.png)

2.Why you use DHF1K Hollywood2 and UCFsports as validation set in train_DSL.py? And there aren't **splitTrainVal** floder for Hollywood2.
![image](https://user-images.githubusercontent.com/67355297/137278378-b0654d44-1875-4918-a9e9-d8c6eb96acb4.png)
But i view that in the paper:
![image](https://user-images.githubusercontent.com/67355297/137278703-16220c9f-dc12-4111-8578-2cf0356d3e59.png)

Looking forward to hearing from you.Thank you so much！

**Comment by GemLuo** [comment]
@simopal6 @cspampin @feiyanhu @yuko95 @ belli13

**Comment by GemLuo** [comment]
@belli13

**Comment by belli13** [comment]
Hi @GemLuo , 
thank you for your interest in our work. 

1. Yes, the results on Table 2 refers to HD2S trained on DHF1K train set and tested on Hollywood2 and UCFSports test sets. In Table 7 we basically report:
  - _Single-source_ : training and testing on same dataset only.
  - _Multi-source_ : training on DHF1K, Hollywhood2 and UCFSports train sets, and testing on a single dataset.
  - _Domain-specific_ : same as Multi-source with HD2S_DSL model.

2. As we stated in the paper, we report the results using only DHF1K validation set. However, during our experiments we tried with different configurations, for example using all the three val sets. The only change to do in train_DSL.py is adding/removing the items in `validation_datasets` list opportunely. We already updated the code to use only DHF1K as val set. 
In the meanwhile, we added splitTrainVal for Hollywood2.

Thank you.

**Comment by GemLuo** [comment]
Thanks for your help! But i still have other questions.
In **_train_DSL.py_** , there are some setting for HD2S_DSL.
![image](https://user-images.githubusercontent.com/67355297/137866611-0ce57bcb-5040-46fc-86f9-c8a5235b8baa.png)
But i think it should be 
![image](https://user-images.githubusercontent.com/67355297/137866922-d27d3b05-cc6d-4037-8317-3b1a1bd5fde7.png), if i want to build a HD2S_DSL model.

**Comment by belli13** [comment]
Exactly.

**Comment by GemLuo** [comment]
I am so glad to receive your reply, thank you so much!

**Comment by GemLuo** [comment]
Could you please show me the python environment dependency and all package's version? I want to know the code for metrics?

**Comment by GemLuo** [comment]
I got the predicted saliency map of DHF1K validation set by loading the HD2S weights that you given in this project. I also train  the HD2S model by myself, but both of them get lower performance than the paper stated. 
![CATNT1T8~7SM6HN~1TNF7QE](https://user-images.githubusercontent.com/67355297/138272312-da7ab963-6591-4483-8a12-4e4b3ea0c525.jpg)

I use pytorch(1.0) and python 3.7.9, and the code for metrics from [https://github.com/wenguanwang/DHF1K/blob/master/code_for_Metrics.zip](url)
And would you mind giving me your contact information like wechat, whatsapp, telegram or other social software? It is not convenient to communicate by e-mail. Please!

**Comment by GemLuo** [comment]
There are a problem after I run the _**train_DSL.py**_. 
/storage/LHY2/Dataset/VideoSaliency/DHF1K
Init Dataset...
Init Dataset Completed.
/storage/LHY2/Dataset/VideoSaliency/Hollywood2_actions
Init Dataset...
Init Dataset Completed.
/storage/LHY2/Dataset/VideoSaliency/ucf
Init Dataset...
Init Dataset Completed.
HD2S_DSL_training_demo_1
Loading weights...
Loading done!
/storage/LHY/anaconda/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train_DSL.py", line 481, in <module>
    main()
  File "train_DSL.py", line 159, in main
    summ = summary(model, input_size=(3, 16, 128, 192))
  File "/storage/LHY/anaconda/envs/pytorch/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/storage/LHY/anaconda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/storage/LHY2/Code/hd2s/models/HD2S_DSL.py", line 280, in forward
    out = self.__getattr__(f'GL_{source_str}')(out)
  File "/storage/LHY/anaconda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/storage/LHY2/Code/hd2s/models/GaussianFilter/LearnableGaussianFilter.py", line 35, in forward
    x = F.conv2d(x, kernel, padding=self.half_k)
_**RuntimeError: Input type (torch.cuda.IntTensor) and weight type (torch.cuda.FloatTensor) should be the same**_

![image](https://user-images.githubusercontent.com/67355297/138387891-1dcc976b-5e65-4256-851f-aabd00b2cdbd.png)
I think the underlined code is the reason that I got this problem. So I want to know why you write this line, it seems like the _**output**_ changed nothing except its type.

**Comment by GemLuo** [comment]
@belli13 @chica9 Could you please show me the python environment dependency and all package's version? I want to know the code for metrics. Please! I hope I can get your help.

**Comment by chica9** [comment]
Hi   #@GemLuo,
we just generated the saliency prediction of the DHF1K validation set using the code in the repo and the provided weights. We also calculated the metrics with the the same matlab code that you have used, and that's our results:

![DemoMetricsMatlab](https://user-images.githubusercontent.com/46196997/139032995-615d3051-0c20-433e-b572-91043234d5e2.PNG)

We have no idea why you got those results. Also, please  note that the matlab code uses a subset of only 50k frames, rather than the whole frames, to compute metrics, so slight differences in results can happen.  

About the RuntimeError you got, we have ran train_DSL.py again and everything works fine. 

> _**RuntimeError: Input type (torch.cuda.IntTensor) and weight type (torch.cuda.FloatTensor) should be the same**_
> 
> ![image](https://user-images.githubusercontent.com/67355297/138387891-1dcc976b-5e65-4256-851f-aabd00b2cdbd.png) I think the underlined code is the reason that I got this problem. So I want to know why you write this line, it seems like the _**output**_ changed nothing except its type.

The type of output in the line you indicated doesn't change, but only the number of digits do.

This is the environment dependency.
[environment.zip](https://github.com/perceivelab/hd2s/files/7424671/environment.zip)

It's better to keep communicating here to leave tracks of our discussion for potentially interested people.

**Comment by GemLuo** [comment]
If it is convenient, could  you please send me the generated result of validation set of DHF1K? @chica9 @belli13
